"""E2E: drive the live app (model loaded) through real clicks and assert audio comes back."""
import os, sys, time
from playwright.sync_api import sync_playwright

URL = sys.argv[1] if len(sys.argv) > 1 else "http://127.0.0.1:7870/"
CHROME = os.path.expandvars(r"%LOCALAPPDATA%\ms-playwright\chromium-1234\chrome-win64\chrome.exe")
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "shots")


def visible_panel(pg):
    return pg.locator(".tabitem:visible").first


with sync_playwright() as p:
    b = p.chromium.launch(executable_path=CHROME) if os.path.exists(CHROME) else p.chromium.launch()
    pg = b.new_page(viewport={"width": 1920, "height": 1080})
    errs = []
    pg.on("console", lambda m: errs.append(m.text) if m.type == "error" else None)
    pg.goto(URL, wait_until="networkidle"); pg.wait_for_timeout(2500)
    print("HEADER", pg.locator(".ov-chips").inner_text().replace("\n", " "))

    # 03 AUTO
    pg.get_by_role("tab", name="03 · Auto").click(); pg.wait_for_timeout(600)
    panel = visible_panel(pg)
    panel.locator("textarea").first.fill("This sentence was generated by clicking the button in the interface.")
    btn = panel.get_by_role("button", name="Generate")
    btn.click()
    pg.wait_for_timeout(400)
    print("BUSY_LABEL", panel.locator("button.primary").inner_text())
    t0 = time.time()
    while time.time() - t0 < 120:
        st = panel.locator(".ov-status textarea").input_value()
        if st:
            break
        pg.wait_for_timeout(500)
    print("AUTO_STATUS", st)
    pg.wait_for_timeout(1200)
    print("AUTO_AUDIO", panel.locator("audio").count() > 0 or panel.locator("[data-testid=waveform-Output]").count() > 0)
    print("BTN_RESTORED", panel.locator("button.primary").inner_text())

    # 02 DESIGN
    pg.get_by_role("tab", name="02 · Design").click(); pg.wait_for_timeout(600)
    panel = visible_panel(pg)
    panel.locator("textarea").first.fill("Good evening. The weather is warm tonight.")
    panel.get_by_label("Or type attributes").fill("male, elderly, low pitch")
    pg.wait_for_timeout(800)
    print("INSTRUCT_PREVIEW", panel.get_by_label("Instruction sent to the model").input_value())
    panel.get_by_role("button", name="Generate").click()
    t0 = time.time(); st = ""
    while time.time() - t0 < 120:
        st = panel.locator(".ov-status textarea").input_value()
        if st:
            break
        pg.wait_for_timeout(500)
    print("DESIGN_STATUS", st)

    # 04 BATCH mode toggling
    pg.get_by_role("tab", name="04 · Batch").click(); pg.wait_for_timeout(600)
    panel = visible_panel(pg)
    vis = lambda lbl: panel.get_by_label(lbl).first.is_visible()
    print("BATCH_AUTO  saved/gender:", vis("Saved voice"), vis("Gender"))
    panel.get_by_label("Designed voice").check(); pg.wait_for_timeout(600)
    print("BATCH_DESIGN saved/gender:", vis("Saved voice"), vis("Gender"))

    # 05 HISTORY
    pg.get_by_role("tab", name="05 · History").click(); pg.wait_for_timeout(600)
    panel = visible_panel(pg)
    panel.get_by_role("button", name="Refresh").click(); pg.wait_for_timeout(1500)
    print("HISTORY_META_HAS_SEED", "seed" in panel.inner_text())

    print("HEADER_AFTER", pg.locator(".ov-chips").inner_text().replace("\n", " "))
    print("ERROR_BADGES", pg.locator(".toast-body.error").count())
    print("CONSOLE_ERRORS", errs[:5])
    pg.screenshot(path=os.path.join(OUT, "e2e_history.png"), full_page=True)
    pg.get_by_role("tab", name="03 · Auto").click(); pg.wait_for_timeout(600)
    pg.screenshot(path=os.path.join(OUT, "e2e_auto.png"), full_page=True)
    b.close()
